##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://akash.network/
# Discord or Telegram project: https://discord.gg/ybKMsYYZkx
# Twitter: https://twitter.com/akashnet_
# Explorer: https://www.mintscan.io/akash/
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: dimokus88/ubuntu:1.3
    env:
      - "MY_ROOT_PASSWORD=" #Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=Akash" # Node name.Имя ноды.
      - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
      - "GITHUB_REPOSITORY=https://github.com/ovrclk/akash.git"
      - "SNAP_RPC=https://rpc-akash.ecostake.com:443"
      - "SNAPSHOT=https://snapshots.polkachu.com/snapshots/akash/akash_9248033.tar.lz4" # use actual snapshot link https://polkachu.com/tendermint_snapshots/akash
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s  https://raw.githubusercontent.com/Dimokus88/Akash-Nodes-Lab/main/Mainnets/Akash%20Network/main.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
