##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://sentinel.co/
# Discord or Telegram project: https://discord.com/invite/mmAA8qF
# Twitter: https://twitter.com/Sentinel_co
# Explorer: https://www.mintscan.io/sentinel
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: dimokus88/ubuntu:1.3
    env:
      - "MY_ROOT_PASSWORD=" #Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=Akash" # Node name.Имя ноды.
      - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
      - "BINARY_LINK=https://github.com/sentinel-official/hub/releases/download/v0.10.1/sentinelhub-0.10.1-linux-amd64"
      - "SNAP_RPC=https://rpc.sentinel.co:443"
      - "PEER=0393c19b176d1cf8bc560c5a8fa990301deb1a7e@135.181.188.20:26656,abc27c91439681b1e7fa4b08b54ebbcc42855973@195.201.63.87:46656,072e3674970c8ef464ee3c2d9ad1d0c709384e62@135.181.55.244:26656,f6f60444040f9f2067519d3f1a1e6c8094cf5664@65.108.195.12:26656,1fe8fddc8a63641774e50ff4518e022c1529fc20@95.216.230.148:26656,36b67a90b368716bb9ce3e47f5198816405c4de3@95.217.127.28:26656"
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s  https://raw.githubusercontent.com/Dimokus88/Akash-Nodes-Lab/main/Mainnets/Sentinel/main.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
