# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://okp4.network/
# Discord or Telegram project: https://discord.com/invite/okp4
# Twitter: https://twitter.com/OKP4_Protocol
# Explorer: https://explorer.nodestake.top/okp4-testnet/
---
version: "2.0"
services:
  app:
    image: dimokus88/ubuntu:1.3
    env:
      - "MY_ROOT_PASSWORD=" # Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=Akash" # Node name. Имя ноды.
      - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
      - "GITHUB_REPOSITORY=https://github.com/okp4/okp4d.git"
      - "SNAP_RPC=http://rpc.okp.ppnv.space:6657"  
      - "PEER=994c9398e55947b2f1f45f33fbdbffcbcad655db@okp4-testnet.nodejumper.io:29656,9d53d896fe92947f8955356191ec0d8c48ce5c98@143.198.179.16:26656,4a46d3ebb46d154c2e9a80f902de331564e12ecb@49.12.216.13:60756,614bbd8582094dd40655ebf74feac81fd0eab530@95.216.252.32:26656,bf6655b16b995a5ebc9bac48411f89d6b832d252@116.202.21.210:26656,94ae99b5efbbcfc26b70122c2d79f82588c14762@109.107.191.202:26656,08f5473f079950c31b94de36c844e1e42e75fede@rpc.okp.ppnv.space:06656,a5ca20b9cd9cb4b0f320a8b117aa922a866bf870@161.35.215.48:26656"
      - "BINARY_VERSION=e3110770a275c049468669e3dd3a35ea551f4f1e"
# If the node is not syncing, connect via ssh and download the snapshot using the command below. 
# Если нода не синхронизируется - подключитесь по ssh и скачайте снепшот с помощью команды ниже.
# sudo curl -s  https://raw.githubusercontent.com/Dimokus88/Akash-Nodes-Lab/main/Active_testnets/okp4/snap.sh | bash
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s  https://raw.githubusercontent.com/Dimokus88/universe/main/node.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi   
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
