##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://www.seinetwork.io/
# Discord or Telegram project: https://t.me/seinetwork
# Twitter: https://twitter.com/SeiNetwork
# Explorer: https://sei.explorers.guru/
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: dimokus88/ubuntu:1.3
    env:
      - "MY_ROOT_PASSWORD=" #Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=Akash" # Node name.Имя ноды.
      - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
      - "GITHUB_REPOSITORY=https://github.com/sei-protocol/sei-chain.git"
      - "SNAP_RPC=https://sei-testnet.nodejumper.io:443"
      - "GENESIS=https://raw.githubusercontent.com/sei-protocol/testnet/main/sei-incentivized-testnet/genesis.json"
      - "DENOM=usei"
      - "PEER=c542c905caa475de4fd9ecca401af29dab5dbee5@135.181.59.162:11956,d5bccc44a3d3089e093e3597ffc7d1dc5250243e@188.40.122.98:36659,c2c02622883f3f3bb56e770b795cce1776b35964@65.109.85.170:31656,b53bb8778a478cde3266569291a1184dec88a3fd@65.108.206.118:60956,b1f7e49b8fd8565cab4cb4c4a0d365c5aeb19c38@65.21.225.178:26656,e890fcf9735a3cbfb236b8c4f75d0110c9988776@65.108.136.152:29656,05c5c96e0a1911b1cb0415fe3bcee6cf1f7a4395@65.108.131.190:28356,1fc581acd401fb38d1f0c1a4b57ece6c096b3a98@65.108.231.124:14656,bd502966bcc7866969f5230a02a3c35c31246d05@213.239.217.52:31656"
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s  https://raw.githubusercontent.com/Dimokus88/universe/main/node.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
