---
version: "2.0"

services:
  node:
    image: thorax/erigon:stable
    command:
      - "sh"
      - "-c"	
    args:
      - 'mkdir -p /home/erigon/datadir/; mkdir -p /home/erigon/jwtsecret;
      erigon --chain=goerli --datadir="/home/erigon/datadir/" --authrpc.jwtsecret="/home/erigon/jwtsecret" --snapshots=true --externalcl --http.api=engine,eth,net --prune.r.before=4367322 --prune htc --http.vhosts "*" --http.port 8545 --http.addr 0.0.0.0 --http.corsdomain "*"'
    expose:
      - port: 30303
        as: 30303
        to:
          - global: true
      - port: 8545
        as: 8545
        to:
          - global: true
      - port: 8546
        as: 8546
        to:
          - global: true
      - port: 8547
        as: 8547
        to:
          - global: true
      - port: 8551
        as: 8551
        to:
          - service: consensus
  consensus:
    image: sigp/lighthouse:latest
    env:
      - LINK_VALIDATOR_KEYS=https://drive.google.com/uc?export=download&id=1EraYfMU2sVlInv-Ko-zvgeH_6dvGgNLd
      - ACCOUNT_ETH_PASS=31081988
      - RECEPIENT=0x9aB137929b89C2c5F47ca43e9D728186D13DF349
    command:
      - "bash"
      - "-c"
    args:
      - 'mkdir /home/lighthouse ; mkdir -p /home/erigon/jwtsecret ; apt-get update && apt-get upgrade -y; apt install wget tar -y;
      wget -O /root/validator_keys.tar "$LINK_VALIDATOR_KEYS";  tar -xf /root/validator_keys.tar ; echo $ACCOUNT_ETH_PASS > /validator_keys/pass.txt ;
      lighthouse --network goerli account validator import --directory /validator_keys/ --datadir /var/lib/lighthouse --password-file /validator_keys/pass.txt --reuse-password; rm /validator_keys/pass.txt; sleep 1m ;
      lighthouse bn --network goerli --datadir /var/lib/lighthouse --http --execution-endpoint http://node:8551 --execution-jwt /home/erigon/jwtsecret/jwt.hex --metrics --suggested-fee-recipient $RECEPIENT'
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 2Gi
        storage:
          size: 200Gi
    consensus:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 4Gi
        storage:
          size: 30Gi

         
  placement:
    akash: 
      pricing:
        node:
          denom: uakt
          amount: 10000000
        consensus:
          denom: uakt
          amount: 10000000
deployment:
  node:
    akash:
      profile: node
      count: 1 
  consensus:
    akash:
      profile: consensus
      count: 1 
