---
version: "2.0"

services:
  node:
    image: thorax/erigon:stable
    command:
      - "sh"
      - "-c"	
    args:
      - 'erigon --chain=goerli --snapshots=true --externalcl --http.api=engine,eth,net --prune.r.before=4367322 --prune htc --http.vhosts "*" --http.port 8545 --http.addr 0.0.0.0 --http.corsdomain "*"'
    expose:
      - port: 30303
        as: 30303
        to:
          - global: true
      - port: 8545
        as: 8545
        to:
          - global: true
      - port: 8546
        as: 8546
        to:
          - global: true
      - port: 8547
        as: 8547
        to:
          - global: true
      - port: 8551
        as: 8551
        to:
          - service: consensus
  consensus:
    image: sigp/lighthouse:latest
    env:
      - LINK_VALIDATOR_KEYS=
      - ACCOUNT_ETH_PASS=
      - RECEPIENT=
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update && apt-get upgrade -y; apt install ssh wget tar -y;
      echo "PermitRootLogin yes" >> /etc/ssh/sshd_config; (echo 111111; echo 111111) | passwd root && service ssh restart;
      wget -O /data/validator_keys.tar "$LINK_VALIDATOR_KEYS";  tar -C /data/ -xf /data/validator_keys.tar ; echo $ACCOUNT_ETH_PASS > /data/validator_keys/pass.txt ;
      lighthouse --network goerli account validator import --directory /data/validator_keys/ --password-file /data/validator_keys/pass.txt --reuse-password; rm /data/validator_keys/pass.txt; sleep 10m ;
      lighthouse bn --network goerli --http --http --checkpoint-sync-url=https://prater-checkpoint-sync.stakely.io --execution-endpoint http://node:8551 --execution-jwt /home/erigon/.local/share/erigon/goerli/jwt.hex --metrics --suggested-fee-recipient $RECEPIENT'
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 8Gi
        storage:
          size: 200Gi
    consensus:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 4Gi
        storage:
          size: 30Gi

         
  placement:
    akash: 
      pricing:
        node:
          denom: uakt
          amount: 10000000
        consensus:
          denom: uakt
          amount: 10000000
deployment:
  node:
    akash:
      profile: node
      count: 1 
  consensus:
    akash:
      profile: consensus
      count: 1 
