---
version: '2'
services:
  testnet-node:
    image: concordium/testnet-node:latest
    expose:
      - port: 10001
        proto: tcp
        to:
          - service: testnet-node-collector
      - port: 20001
        as: 20001
        to:
          - global: true
      - port: 8889
        as: 8889
        to:
          - global: true
    env:
      - CONCORDIUM_NODE_LISTEN_PORT=8889
      - CONCORDIUM_NODE_CONNECTION_DESIRED_NODES=5
      - CONCORDIUM_NODE_CONNECTION_MAX_ALLOWED_NODES=10
      - CONCORDIUM_NODE_RPC_SERVER_ADDR=0.0.0.0
      - CONCORDIUM_NODE_RPC_SERVER_PORT=10001
      - CONCORDIUM_NODE_GRPC2_LISTEN_PORT=20001
      - CONCORDIUM_NODE_GRPC2_LISTEN_ADDRESS=0.0.0.0
      - CONCORDIUM_NODE_CONNECTION_HARD_CONNECTION_LIMIT=20
      - CONCORDIUM_NODE_CONNECTION_THREAD_POOL_SIZE=2
      - CONCORDIUM_NODE_CONNECTION_BOOTSTRAPPING_INTERVAL=1800
      - CONCORDIUM_NODE_BAKER_HASKELL_RTS_FLAGS=-N2,-I0
    args:
      - "/concordium-node"
      - "--config-dir=/mnt/"
      - "--data-dir=/mnt/" 
      - "--genesis-data-file=/testnet-genesis.dat"
      - "--bootstrap-node=bootstrap.testnet.concordium.com:8888"

  testnet-node-collector:
    image: concordium/testnet-node:latest
    env:
      - CONCORDIUM_NODE_COLLECTOR_NODE_NAME=<YOUR_NODE_NAME>
      - CONCORDIUM_NODE_COLLECTOR_URL=https://dashboard.testnet.concordium.com/nodes/post
      - CONCORDIUM_NODE_COLLECTOR_COLLECT_INTERVAL=5000
      - CONCORDIUM_NODE_COLLECTOR_GRPC_HOST=http://testnet-node:10001
    args:
      - '/node-collector'

profiles:
  compute:
    testnet-node:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 45Gi
    testnet-node-collector:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 10Gi
    
  placement:
    westcoast:
      attributes:
        host: akash
      pricing:
        testnet-node: 
          denom: uakt
          amount: 10000
        testnet-node-collector: 
          denom: uakt
          amount: 10000
        


deployment:
  testnet-node:
    westcoast:
      profile: testnet-node
      count: 1 
  testnet-node-collector:
    westcoast:
      profile: testnet-node-collector
      count: 1 
