---
version: "2.0"
services:
  app:
    image: ubuntu:latest 
    env:
      - "PASS_SSH="   
      - "LINK_BINARY=https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-x86_64-linux-gnu.tar.gz"
      - "PRUNE=20000"
    
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update && apt-get upgrade -y ;
        apt-get install -y  curl ;
        curl https://raw.githubusercontent.com/Dimokus88/Akash-Nodes-Lab/main/Mainnets/Bitcoin/bitsnap.sh | bash'
    params:
      storage:
        data:
          mount: /root/
    expose:
      - port: 80
        as: 80
        to:
          - global: true
        accept:
          - "bitcoin.provider.palmito.duckdns.org"
      - port: 8333
        as: 8333
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 2Gi
        storage:
          - size: 3Gi
          - name: data
            size: 50Gi
            attributes:
              persistent: true
              class: beta1
         
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 1000000
deployment:
  app:
    akash:
      profile: app
      count: 1 
