---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.3
    env:
      - "MY_ROOT_PASSWORD=" # Root password far a ssh connection. Пароль root для подключения по ssh.

    command:
      - "bash"
      - "-c"
    args:
      - 'echo "PermitRootLogin yes" >> /etc/ssh/sshd_config ;
        (echo $PASS; echo $PASS) | passwd root ; 
        service ssh start;
        sleep infinity'
    expose:
      - port: 22
        as: 22
        to:
          - global: true
      - port: 1790
        as: 1790
        to:
          - global: true
      - port: 1789
        as: 1789
        to:
          - global: true
      - port: 8000
        as: 8000
        to:
          - global: true      
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 3.0
        memory:
          size: 5Gi
        storage:
          size: 50Gi

         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 100000
deployment:
  app:
    akash:
      profile: app
      count: 1 
