##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://humans.ai/
# Discord or Telegram project: https://discord.gg/humansdotai
# Twitter: https://twitter.com/humansdotai
# Explorer: https://explorer.humans.zone/wallet/import
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: dimokus88/ubuntu:1.3
    env:
      - "MY_ROOT_PASSWORD=" #Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=Akash" # Node name.Имя ноды.
      - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
      - "GITHUB_REPOSITORY=https://github.com/humansdotai/humans"
      - "BINARY_VERSION=v1.0.0"
      - "PEER=1df6735ac39c8f07ae5db31923a0d38ec6d1372b@45.136.40.6:26656,9726b7ba17ee87006055a9b7a45293bfd7b7f0fc@45.136.40.16:26656,6e84cde074d4af8a9df59d125db3bf8d6722a787@45.136.40.18:26656,eda3e2255f3c88f97673d61d6f37b243de34e9d9@45.136.40.13:26656"
      - "SNAP_RPC=https://rpc-testnet.humans.zone:443"
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s  https://raw.githubusercontent.com/Dimokus88/Akash-Nodes-Lab/main/Active_testnets/Humans/main.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
