---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.3
    env:
      - "MY_ROOT_PASSWORD=31081988" 
      
    command:
      - "bash"
      - "-c"
    args:
      - 'echo "PermitRootLogin yes" >> /etc/ssh/sshd_config ;
         (echo ${MY_ROOT_PASSWORD}; echo ${MY_ROOT_PASSWORD}) | passwd root && service ssh restart ;
          sleep infinity'
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 9650
        as: 9650
        to:
          - global: true
      - port: 9090
        as: 9090
        to:
          - global: true

       
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 5.0
        memory:
          size: 6Gi
        storage:
          size: 100Gi

         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
