---
version: "2.0"
endpoints:
  YOUR_ENDPOINT_NAME:  # WARRING! SELECT UNIQ ENDPOINT NAME!
    kind: ip
services:
  app:
    image: ubuntu:22.04
    expose:
      - port: 80
        as: 80
        proto: tcp
        to:
          - global: true            
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 31244
        as: 31244
        proto: tcp
        to:
          - global: true
            ip: YOUR_ENDPOINT_NAME # ENDPOINT NAME FROM STRING 4
      - port: 31245
        as: 31245
        proto: tcp
        to:
          - global: true
            ip: YOUR_ENDPOINT_NAME # ENDPOINT NAME FROM STRING 4
        
    env:
     - "my_discord_id="
     - "my_wallet_privkey=" #Massa wallet privat key
     - "my_root_password=" #For ssh connection
     - "wait=600" #Set roll check frequency in seconds. Установите частоту проверки роллов в секундах.
     - "MASSA_LINK=https://github.com/massalabs/massa/releases/download/TEST.18.0/massa_TEST.18.0_release_linux.tar.gz"
     - "pass="
   
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install -y  curl ; curl -s  https://raw.githubusercontent.com/Dimokus88/Akash-Nodes-Lab/main/Active_testnets/Massa/main.sh  | bash ; sleep infinity '

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 8Gi
        storage:
          size: 50Gi

  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
